<a href="https://colab.research.google.com/github/vijaykeerthi21/DATA-ANALYSIS/blob/main/Descriptive-Statistical-Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
#To read a csv file and assign to dataframe(df)
df_main =pd.read_csv("/content/crop_production.csv")

In [ ]:
#To check number of row and columns
df_main.shape

(85734, 7)

In [ ]:
#To check the top values present in dataFrame
df_main.head()

,State_Name,District_Name,Crop_Year,Season,Crop,Area,Production
0,Andaman and Nicobar Islands,NICOBARS,2000.0,Kharif,Arecanut,1254.0,2000.0
1,Andaman and Nicobar Islands,NICOBARS,2000.0,Kharif,Other Kharif pulses,2.0,1.0
2,Andaman and Nicobar Islands,NICOBARS,2000.0,Kharif,Rice,102.0,321.0
3,Andaman and Nicobar Islands,NICOBARS,2000.0,Whole Year,Banana,176.0,641.0
4,Andaman and Nicobar Islands,NICOBARS,2000.0,Whole Year,Cashewnut,720.0,165.0

In [ ]:
#It gives a brief about data in df
#ex : column names, null values,count,data_types
df_main.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 85734 entries, 0 to 85733
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   State_Name     85734 non-null  object
 1   District_Name  85733 non-null  object
 2   Crop_Year      85733 non-null  float64
 3   Season         85733 non-null  object
 4   Crop           85733 non-null  object
 5   Area           85733 non-null  float64
 6   Production     83844 non-null  float64
dtypes: float64(3), object(4)
memory usage: 4.6+ MB

In [ ]:
#To see the name of the columns in df
df_main.columns

Index(['State_Name', 'District_Name', 'Crop_Year', 'Season', 'Crop', 'Area',
       'Production'],
      dtype='object')

DESCRIPTIVE  STATISTICAL DATA ANALYSIS

In [ ]:
#To know the statistical info with object data-type
 df_main.describe(include=[object])

       State_Name District_Name       Season   Crop
count       85734         85733        85733  85733
unique         15           246            6     91
top         Bihar       BIJAPUR  Kharif        Rice
freq        18885           945        32759   5708

In [ ]:
#T0 know the maximum value in column
df_main["Production"].max()

780162000.0

In [ ]:
#To knoe the standard deviation
df_main["Production"].std()

9522879.428644001

In [ ]:
#To know the statistical info which involves int data-type
df_main.describe()

          Crop_Year           Area    Production
count  85733.000000   85733.000000  8.384400e+04
mean    2005.819906    9055.442826  2.695499e+05
std        4.924678   31517.403235  9.522879e+06
min     1997.000000       0.100000  0.000000e+00
25%     2002.000000      86.000000  1.000000e+02
50%     2006.000000     518.000000  7.260000e+02
75%     2010.000000    3334.000000  6.404000e+03
max     2014.000000  877029.000000  7.801620e+08

In [ ]:
#To know the count of every columns data in Data Frame

df_main.count()

State_Name       85734
District_Name    85733
Crop_Year        85733
Season           85733
Crop             85733
Area             85733
Production       83844
dtype: int64

In [ ]:
#To know the count of a single columns data in Data Frame
df1 = df_main["Production"]
df1

0         2000.0
1            1.0
2          321.0
3          641.0
4          165.0
          ...
85729       45.0
85730    57575.0
85731        5.0
85732     1922.0
85733        NaN
Name: Production, Length: 85734, dtype: float64

In [ ]:
df1.describe()

count    8.384400e+04
mean     2.695499e+05
std      9.522879e+06
min      0.000000e+00
25%      1.000000e+02
50%      7.260000e+02
75%      6.404000e+03
max      7.801620e+08
Name: Production, dtype: float64

In [ ]:
#To know the statistical info for all data present in DataFrame
df_main.describe(include='all')

,State_Name,District_Name,Crop_Year,Season,Crop,Area,Production
count,85734,85733,85733.000000,85733,85733,85733.000000,8.384400e+04
unique,15,246,NaN,6,91,NaN,NaN
top,Bihar,BIJAPUR,NaN,Kharif,Rice,NaN,NaN
freq,18885,945,NaN,32759,5708,NaN,NaN
mean,NaN,NaN,2005.819906,NaN,NaN,9055.442826,2.695499e+05
std,NaN,NaN,4.924678,NaN,NaN,31517.403235,9.522879e+06
min,NaN,NaN,1997.000000,NaN,NaN,0.100000,0.000000e+00
25%,NaN,NaN,2002.000000,NaN,NaN,86.000000,1.000000e+02
50%,NaN,NaN,2006.000000,NaN,NaN,518.000000,7.260000e+02
75%,NaN,NaN,2010.000000,NaN,NaN,3334.000000,6.404000e+03
max,NaN,NaN,2014.000000,NaN,NaN,877029.000000,7.801620e+08

In [ ]:
#TO know which data-type present in Each column in Data frame
df_main.dtypes

State_Name        object
District_Name     object
Crop_Year        float64
Season            object
Crop              object
Area             float64
Production       float64
dtype: object

Conclusion : These are the Descriptive  Statistical Analysis